zookeeper:
  image: oddpoet/zookeeper
  hostname: zookeeper
  command:
    - "2181"
  ports:
    - "2181:2181"
database:
  image: mongo:latest
  command: 
	- mongod --smallfiles
  ports:
	- "27017:27017"
commandaccounts:
  image: java:8
  volumes:
	- ./commandside-web-accounts/build/libs/:/app
  command: 
	- java -jar /app/commandside-web-accounts.jar
  ports:
    - "8080:8080"
  links:
	- database
    - zookeeper